baseURL = 'https://xbh-ux.github.io/'
title = '我的博客'
theme = 'hugo-book'
defaultContentLanguage = 'zh'

[[module.mounts]]
  source = 'content'
  target = 'content'
  files = ['! Templates/**', '! templates/**']

[languages]
  [languages.zh]
    locale = 'zh-cn'
    label = '中文'
    weight = 1

[params]
  BookSection = 'posts'
  BookToC = true
  BookSearch = true
  BookTheme = "auto"
