baseURL = 'https://xbh-ux.github.io/'
title = '我的博客'
theme = 'PaperMod'
defaultContentLanguage = 'zh'

[languages]
  [languages.zh]
    locale = 'zh-cn'
    label = '中文'
    weight = 1

[params]
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true